### PR TITLE
Created simple Web page using HTML and CSS

### PR DESCRIPTION
**Pull request by tylher**
My first Microverse project ready for review

- Added HTML file
- Added CSS file for styling
- Added a .gitignore file which allows to ignore "test.md" file

### CODE REVIEW

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## Hi @tylher 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- test.md file is mentioned in .gitignore file. :heavy_check_mark:

## Required Changes ♻️
- [x] Pull Request should have a descriptive title and description telling you what changes are inside the Pull request. Please update the description of your Pull request.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ]  Please update your README file with the correct description and information for the project
- [ ]  Please use camel case for your commit messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tylher** [comment]
Hey, @thecodechaser thank you for the observation and corrections. I am not quite sure about the pull request description but I changed the title, please let me know if you are okay with it.

**Comment by thecodechaser** [comment]
Hello @tylher 
Your PR has description "My first Microverse project ready for review". Please update it, It should tell what changes are inside this PR
You can use bullet points
- Added HTML file
- Added CSS file
- XYZ

**Comment by tylher** [comment]
Oh my bad, thank you @thecodechaser  I changed it already, let me know what you think.

**Comment by thecodechaser** [comment]
Hello, @tylher It's perfect now, You are good to go. Good luck. 👍

**Comment by tylher** [comment]
Also what changes can I make to my README file, this is my first time writing one.
I feel like I am not getting it.

**Review by elmar8287 — COMMENTED** [review]
Hi @tylher, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
